// Code generated by protoc-gen-go. DO NOT EDIT.
// source: game.proto

package service

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Game_Platform int32

const (
	Game_PC      Game_Platform = 0
	Game_MOBILE  Game_Platform = 1
	Game_CONSOLE Game_Platform = 2
	Game_ETC     Game_Platform = 3
)

var Game_Platform_name = map[int32]string{
	0: "PC",
	1: "MOBILE",
	2: "CONSOLE",
	3: "ETC",
}

var Game_Platform_value = map[string]int32{
	"PC":      0,
	"MOBILE":  1,
	"CONSOLE": 2,
	"ETC":     3,
}

func (x Game_Platform) String() string {
	return proto.EnumName(Game_Platform_name, int32(x))
}

func (Game_Platform) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{6, 0}
}

type CreateGameRequest struct {
	Game                 *Game    `protobuf:"bytes,1,opt,name=game,proto3" json:"game,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateGameRequest) Reset()         { *m = CreateGameRequest{} }
func (m *CreateGameRequest) String() string { return proto.CompactTextString(m) }
func (*CreateGameRequest) ProtoMessage()    {}
func (*CreateGameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{0}
}

func (m *CreateGameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateGameRequest.Unmarshal(m, b)
}
func (m *CreateGameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateGameRequest.Marshal(b, m, deterministic)
}
func (m *CreateGameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateGameRequest.Merge(m, src)
}
func (m *CreateGameRequest) XXX_Size() int {
	return xxx_messageInfo_CreateGameRequest.Size(m)
}
func (m *CreateGameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateGameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateGameRequest proto.InternalMessageInfo

func (m *CreateGameRequest) GetGame() *Game {
	if m != nil {
		return m.Game
	}
	return nil
}

type CreateGameResponse struct {
	ErrorCode            int32    `protobuf:"varint,1,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	ErrorMessage         string   `protobuf:"bytes,2,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	Game                 *Game    `protobuf:"bytes,3,opt,name=game,proto3" json:"game,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateGameResponse) Reset()         { *m = CreateGameResponse{} }
func (m *CreateGameResponse) String() string { return proto.CompactTextString(m) }
func (*CreateGameResponse) ProtoMessage()    {}
func (*CreateGameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{1}
}

func (m *CreateGameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateGameResponse.Unmarshal(m, b)
}
func (m *CreateGameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateGameResponse.Marshal(b, m, deterministic)
}
func (m *CreateGameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateGameResponse.Merge(m, src)
}
func (m *CreateGameResponse) XXX_Size() int {
	return xxx_messageInfo_CreateGameResponse.Size(m)
}
func (m *CreateGameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateGameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateGameResponse proto.InternalMessageInfo

func (m *CreateGameResponse) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *CreateGameResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *CreateGameResponse) GetGame() *Game {
	if m != nil {
		return m.Game
	}
	return nil
}

type GetGameRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGameRequest) Reset()         { *m = GetGameRequest{} }
func (m *GetGameRequest) String() string { return proto.CompactTextString(m) }
func (*GetGameRequest) ProtoMessage()    {}
func (*GetGameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{2}
}

func (m *GetGameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGameRequest.Unmarshal(m, b)
}
func (m *GetGameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGameRequest.Marshal(b, m, deterministic)
}
func (m *GetGameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGameRequest.Merge(m, src)
}
func (m *GetGameRequest) XXX_Size() int {
	return xxx_messageInfo_GetGameRequest.Size(m)
}
func (m *GetGameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetGameRequest proto.InternalMessageInfo

func (m *GetGameRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetGameResponse struct {
	ErrorCode            int32    `protobuf:"varint,1,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	ErrorMessage         string   `protobuf:"bytes,2,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	Game                 *Game    `protobuf:"bytes,3,opt,name=game,proto3" json:"game,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGameResponse) Reset()         { *m = GetGameResponse{} }
func (m *GetGameResponse) String() string { return proto.CompactTextString(m) }
func (*GetGameResponse) ProtoMessage()    {}
func (*GetGameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{3}
}

func (m *GetGameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGameResponse.Unmarshal(m, b)
}
func (m *GetGameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGameResponse.Marshal(b, m, deterministic)
}
func (m *GetGameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGameResponse.Merge(m, src)
}
func (m *GetGameResponse) XXX_Size() int {
	return xxx_messageInfo_GetGameResponse.Size(m)
}
func (m *GetGameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetGameResponse proto.InternalMessageInfo

func (m *GetGameResponse) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *GetGameResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *GetGameResponse) GetGame() *Game {
	if m != nil {
		return m.Game
	}
	return nil
}

type GetGamesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGamesRequest) Reset()         { *m = GetGamesRequest{} }
func (m *GetGamesRequest) String() string { return proto.CompactTextString(m) }
func (*GetGamesRequest) ProtoMessage()    {}
func (*GetGamesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{4}
}

func (m *GetGamesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGamesRequest.Unmarshal(m, b)
}
func (m *GetGamesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGamesRequest.Marshal(b, m, deterministic)
}
func (m *GetGamesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGamesRequest.Merge(m, src)
}
func (m *GetGamesRequest) XXX_Size() int {
	return xxx_messageInfo_GetGamesRequest.Size(m)
}
func (m *GetGamesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGamesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetGamesRequest proto.InternalMessageInfo

type GetGamesResponse struct {
	ErrorCode            int32    `protobuf:"varint,1,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	ErrorMessage         string   `protobuf:"bytes,2,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	Games                []*Game  `protobuf:"bytes,3,rep,name=games,proto3" json:"games,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGamesResponse) Reset()         { *m = GetGamesResponse{} }
func (m *GetGamesResponse) String() string { return proto.CompactTextString(m) }
func (*GetGamesResponse) ProtoMessage()    {}
func (*GetGamesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{5}
}

func (m *GetGamesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGamesResponse.Unmarshal(m, b)
}
func (m *GetGamesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGamesResponse.Marshal(b, m, deterministic)
}
func (m *GetGamesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGamesResponse.Merge(m, src)
}
func (m *GetGamesResponse) XXX_Size() int {
	return xxx_messageInfo_GetGamesResponse.Size(m)
}
func (m *GetGamesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGamesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetGamesResponse proto.InternalMessageInfo

func (m *GetGamesResponse) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *GetGamesResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *GetGamesResponse) GetGames() []*Game {
	if m != nil {
		return m.Games
	}
	return nil
}

type Game struct {
	Id                   int32         `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	GameCode             int32         `protobuf:"varint,2,opt,name=gameCode,proto3" json:"gameCode,omitempty"`
	Name                 string        `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Platform             Game_Platform `protobuf:"varint,4,opt,name=platform,proto3,enum=Game_Platform" json:"platform,omitempty"`
	LandingUrl           string        `protobuf:"bytes,5,opt,name=landingUrl,proto3" json:"landingUrl,omitempty"`
	ImageUrl             string        `protobuf:"bytes,6,opt,name=imageUrl,proto3" json:"imageUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Game) Reset()         { *m = Game{} }
func (m *Game) String() string { return proto.CompactTextString(m) }
func (*Game) ProtoMessage()    {}
func (*Game) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{6}
}

func (m *Game) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game.Unmarshal(m, b)
}
func (m *Game) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game.Marshal(b, m, deterministic)
}
func (m *Game) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game.Merge(m, src)
}
func (m *Game) XXX_Size() int {
	return xxx_messageInfo_Game.Size(m)
}
func (m *Game) XXX_DiscardUnknown() {
	xxx_messageInfo_Game.DiscardUnknown(m)
}

var xxx_messageInfo_Game proto.InternalMessageInfo

func (m *Game) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Game) GetGameCode() int32 {
	if m != nil {
		return m.GameCode
	}
	return 0
}

func (m *Game) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Game) GetPlatform() Game_Platform {
	if m != nil {
		return m.Platform
	}
	return Game_PC
}

func (m *Game) GetLandingUrl() string {
	if m != nil {
		return m.LandingUrl
	}
	return ""
}

func (m *Game) GetImageUrl() string {
	if m != nil {
		return m.ImageUrl
	}
	return ""
}

func init() {
	proto.RegisterEnum("Game_Platform", Game_Platform_name, Game_Platform_value)
	proto.RegisterType((*CreateGameRequest)(nil), "CreateGameRequest")
	proto.RegisterType((*CreateGameResponse)(nil), "CreateGameResponse")
	proto.RegisterType((*GetGameRequest)(nil), "GetGameRequest")
	proto.RegisterType((*GetGameResponse)(nil), "GetGameResponse")
	proto.RegisterType((*GetGamesRequest)(nil), "GetGamesRequest")
	proto.RegisterType((*GetGamesResponse)(nil), "GetGamesResponse")
	proto.RegisterType((*Game)(nil), "Game")
}

func init() { proto.RegisterFile("game.proto", fileDescriptor_38fc58335341d769) }

var fileDescriptor_38fc58335341d769 = []byte{
	// 410 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x93, 0xdf, 0x8e, 0x93, 0x40,
	0x14, 0xc6, 0x0b, 0xb4, 0x40, 0x4f, 0x0d, 0x4b, 0x8f, 0x89, 0x41, 0x34, 0x86, 0xcc, 0x55, 0xe3,
	0xc5, 0x24, 0x56, 0x13, 0xef, 0x97, 0x90, 0xc6, 0x64, 0xd7, 0x6e, 0x58, 0xbd, 0xf1, 0x6e, 0x5c,
	0x46, 0x42, 0xc2, 0xbf, 0xce, 0xa0, 0xf1, 0x95, 0xf4, 0xb9, 0x7c, 0x10, 0x33, 0x53, 0xfe, 0x74,
	0xdb, 0x5b, 0xe3, 0x1d, 0xe7, 0x77, 0x0e, 0xf3, 0x7d, 0x70, 0xbe, 0x01, 0xc8, 0x59, 0xc5, 0x69,
	0x2b, 0x9a, 0xae, 0x21, 0x14, 0xd6, 0xb1, 0xe0, 0xac, 0xe3, 0x3b, 0x56, 0xf1, 0x94, 0x1f, 0xbe,
	0x73, 0xd9, 0xe1, 0x73, 0x98, 0xab, 0x91, 0xc0, 0x88, 0x8c, 0xcd, 0x6a, 0xbb, 0xa0, 0xba, 0xa7,
	0x11, 0x39, 0x00, 0x9e, 0xce, 0xcb, 0xb6, 0xa9, 0x25, 0xc7, 0x97, 0xb0, 0xe4, 0x42, 0x34, 0x22,
	0x6e, 0xb2, 0xe3, 0x5b, 0x8b, 0x74, 0x02, 0x48, 0xe0, 0x89, 0x2e, 0x6e, 0xb9, 0x94, 0x2c, 0xe7,
	0x81, 0x19, 0x19, 0x9b, 0x65, 0xfa, 0x88, 0x8d, 0x92, 0xd6, 0xa5, 0x64, 0x04, 0xde, 0x8e, 0x77,
	0xa7, 0xfe, 0x3c, 0x30, 0x8b, 0xac, 0xd7, 0x31, 0x8b, 0x8c, 0xd4, 0x70, 0x35, 0x4e, 0xfc, 0x0f,
	0x47, 0xeb, 0x51, 0x4f, 0xf6, 0x96, 0xc8, 0x01, 0xfc, 0x09, 0xfd, 0x33, 0x0f, 0x2f, 0x60, 0xa1,
	0x04, 0x65, 0x60, 0x45, 0xd6, 0x64, 0xe2, 0xc8, 0xc8, 0x1f, 0x03, 0xe6, 0xaa, 0x3e, 0xff, 0x1d,
	0x18, 0x82, 0xab, 0x26, 0xb4, 0xac, 0xa9, 0xe9, 0x58, 0x23, 0xc2, 0xbc, 0x1e, 0xbe, 0x6a, 0x99,
	0xea, 0x67, 0x7c, 0x0d, 0x6e, 0x5b, 0xb2, 0xee, 0x5b, 0x23, 0xaa, 0x60, 0x1e, 0x19, 0x1b, 0x6f,
	0xeb, 0x69, 0x21, 0x7a, 0xd7, 0xd3, 0x74, 0xec, 0xe3, 0x2b, 0x80, 0x92, 0xd5, 0x59, 0x51, 0xe7,
	0x9f, 0x45, 0x19, 0x2c, 0xf4, 0x29, 0x27, 0x44, 0x69, 0x17, 0x15, 0xcb, 0xb9, 0xea, 0xda, 0xba,
	0x3b, 0xd6, 0xe4, 0x1d, 0xb8, 0xc3, 0x89, 0x68, 0x83, 0x79, 0x17, 0xfb, 0x33, 0x04, 0xb0, 0x6f,
	0xf7, 0xd7, 0x1f, 0x6e, 0x12, 0xdf, 0xc0, 0x15, 0x38, 0xf1, 0xfe, 0xe3, 0xfd, 0xfe, 0x26, 0xf1,
	0x4d, 0x74, 0xc0, 0x4a, 0x3e, 0xc5, 0xbe, 0xb5, 0xfd, 0x65, 0xc0, 0x4a, 0xb9, 0xb9, 0xe7, 0xe2,
	0x47, 0xf1, 0xc0, 0xf1, 0x3d, 0xc0, 0x94, 0x40, 0x44, 0x7a, 0x11, 0xdf, 0xf0, 0x29, 0xbd, 0x8c,
	0x28, 0x99, 0x21, 0x05, 0xa7, 0x5f, 0x11, 0x5e, 0xd1, 0xc7, 0x89, 0x0a, 0x7d, 0x7a, 0x16, 0x20,
	0x32, 0xc3, 0x37, 0xe0, 0x0e, 0x2b, 0xc5, 0xb1, 0x3f, 0x2c, 0x3c, 0x5c, 0xd3, 0xf3, 0x7d, 0x93,
	0xd9, 0x35, 0xf9, 0xe2, 0xc8, 0xa3, 0xcd, 0xdf, 0xe6, 0xb3, 0x9d, 0x68, 0x1f, 0x92, 0x9f, 0xac,
	0x6a, 0x4b, 0xed, 0x9d, 0x0b, 0xaa, 0xc8, 0x57, 0x5b, 0x5f, 0xbc, 0xb7, 0x7f, 0x03, 0x00, 0x00,
	0xff, 0xff, 0xa9, 0xfc, 0xe9, 0x9d, 0x86, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GameServiceClient is the client API for GameService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GameServiceClient interface {
	CreateGame(ctx context.Context, in *CreateGameRequest, opts ...grpc.CallOption) (*CreateGameResponse, error)
	GetGame(ctx context.Context, in *GetGameRequest, opts ...grpc.CallOption) (*GetGameResponse, error)
	GetGames(ctx context.Context, in *GetGamesRequest, opts ...grpc.CallOption) (*GetGamesResponse, error)
}

type gameServiceClient struct {
	cc *grpc.ClientConn
}

func NewGameServiceClient(cc *grpc.ClientConn) GameServiceClient {
	return &gameServiceClient{cc}
}

func (c *gameServiceClient) CreateGame(ctx context.Context, in *CreateGameRequest, opts ...grpc.CallOption) (*CreateGameResponse, error) {
	out := new(CreateGameResponse)
	err := c.cc.Invoke(ctx, "/GameService/CreateGame", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) GetGame(ctx context.Context, in *GetGameRequest, opts ...grpc.CallOption) (*GetGameResponse, error) {
	out := new(GetGameResponse)
	err := c.cc.Invoke(ctx, "/GameService/GetGame", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) GetGames(ctx context.Context, in *GetGamesRequest, opts ...grpc.CallOption) (*GetGamesResponse, error) {
	out := new(GetGamesResponse)
	err := c.cc.Invoke(ctx, "/GameService/GetGames", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameServiceServer is the server API for GameService service.
type GameServiceServer interface {
	CreateGame(context.Context, *CreateGameRequest) (*CreateGameResponse, error)
	GetGame(context.Context, *GetGameRequest) (*GetGameResponse, error)
	GetGames(context.Context, *GetGamesRequest) (*GetGamesResponse, error)
}

// UnimplementedGameServiceServer can be embedded to have forward compatible implementations.
type UnimplementedGameServiceServer struct {
}

func (*UnimplementedGameServiceServer) CreateGame(ctx context.Context, req *CreateGameRequest) (*CreateGameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGame not implemented")
}
func (*UnimplementedGameServiceServer) GetGame(ctx context.Context, req *GetGameRequest) (*GetGameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGame not implemented")
}
func (*UnimplementedGameServiceServer) GetGames(ctx context.Context, req *GetGamesRequest) (*GetGamesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGames not implemented")
}

func RegisterGameServiceServer(s *grpc.Server, srv GameServiceServer) {
	s.RegisterService(&_GameService_serviceDesc, srv)
}

func _GameService_CreateGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).CreateGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GameService/CreateGame",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).CreateGame(ctx, req.(*CreateGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_GetGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).GetGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GameService/GetGame",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).GetGame(ctx, req.(*GetGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_GetGames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGamesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).GetGames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GameService/GetGames",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).GetGames(ctx, req.(*GetGamesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GameService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "GameService",
	HandlerType: (*GameServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateGame",
			Handler:    _GameService_CreateGame_Handler,
		},
		{
			MethodName: "GetGame",
			Handler:    _GameService_GetGame_Handler,
		},
		{
			MethodName: "GetGames",
			Handler:    _GameService_GetGames_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "game.proto",
}
